# Generated by Django 5.1.2 on 2025-01-08 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='preco_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
